"""make datetime columns timezone aware

Revision ID: 1e2570f01fd4
Revises: 32ac5a1aadf9
Create Date: 2026-05-30 04:32:19.587585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2570f01fd4'
down_revision: Union[str, Sequence[str], None] = '32ac5a1aadf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
