"""add post_reactions table

Revision ID: 69160116147b
Revises: 42316227d2aa
Create Date: 2026-06-05 12:04:32.333310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69160116147b'
down_revision: Union[str, Sequence[str], None] = '42316227d2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_slug', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.Enum('LIKE', 'HEART', 'FIRE', 'INSIGHTFUL', name='reactiontype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_slug', 'user_id', 'reaction', name='uq_post_reaction_user')
    )
    op.create_index(op.f('ix_post_reactions_id'), 'post_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_post_reactions_post_slug'), 'post_reactions', ['post_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_reactions_post_slug'), table_name='post_reactions')
    op.drop_index(op.f('ix_post_reactions_id'), table_name='post_reactions')
    op.drop_table('post_reactions')
    # ### end Alembic commands ###
